version: "3.9"
services:
  redis:
    image: redis:7-alpine
    # no host port -> avoids 6379 conflicts
    command: ["redis-server","--appendonly","yes"]
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      REDIS_URL: ${REDIS_URL}
      STRIPE_CHECKOUT_LINK: ${STRIPE_CHECKOUT_LINK}
      STORAGE_DIR: ${STORAGE_DIR}
      PORT_API: ${PORT_API}
    depends_on:
      redis:
        condition: service_healthy
    volumes: [ "./data:/data" ]
    ports: [ "${PORT_API}:8087" ]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      REDIS_URL: ${REDIS_URL}
      STORAGE_DIR: ${STORAGE_DIR}
    depends_on:
      redis:
        condition: service_healthy
    volumes: [ "./data:/data" ]

  static:
    image: nginx:alpine
    depends_on: [api]
    volumes:
      - ./data/sites:/usr/share/nginx/html:ro
    ports: [ "${PORT_STATIC}:80" ]
