version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: mr_redis
    ports: ["6379:6379"]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mr_api
    environment:
      REDIS_URL: redis://redis:6379/0
      STRIPE_CHECKOUT_LINK: ${STRIPE_CHECKOUT_LINK:-}
      STORAGE_DIR: /data
      PORT_API: 8087
    depends_on: [redis]
    volumes: [ "./data:/data" ]
    ports: [ "8087:8087" ]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: mr_worker
    environment:
      REDIS_URL: redis://redis:6379/0
      STORAGE_DIR: /data
    depends_on: [redis]
    volumes: [ "./data:/data" ]

  static:
    image: nginx:alpine
    container_name: mr_static
    depends_on: [api]
    volumes:
      - ./data/sites:/usr/share/nginx/html:ro
    ports: [ "8088:80" ]
